name: GITHUB ACITON yaml auto

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    # 首先copy git仓库到虚拟机上
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          cache: 'pip'
        - run: pip install glob
        - run: pip install yaml
        - run: pip install ruamel.yaml
        # 运行脚本
      - name: Working
        run: python ./webstack_yaml_win.py