name: yaml_auto

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install requests
      run: pip install ruamel.yaml

    - name: Update paper list
      run: python webstack_yaml_linux.py
    - name: commit
      run: |
        git config --global user.email github-actions[bot]@users.noreply.github.com
        git config --global user.name github-actions[bot]
        git add .
        git commit -m "yaml_auto" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
